### ISSUE TITLE
can't mount/list  admin share in non interactive mode

### ISSUE THREAD

**Issue by nikaiw** [jfjallid/go-shareenum#10]
Hello thanks for this awesome project

is there a reason for the -1 in https://github.com/jfjallid/go-shareenum/blob/b9c43f43e1cb06c2bae55f6788e43361f25b3a9c/main.go#L706 instead of having name := netshare.Name ?

This is preventing the mount and listing of administratives share ending with $ in non interactive mode.e.g The program attempt to mount c instead of c$

**Comment by jfjallid** [comment]
Thanks for spotting that.
There was a change in go-smb library with null termination of the share names no longer being returned to the client.
Forgot to update this repo once I made that change in go-smb.
