### ISSUE TITLE
Logon failed

### ISSUE THREAD

**Issue by wqk151** [jfjallid/go-shareenum#9]
Hello, my username like:`model@example.com`,and password like `a~5+SkUdK0E_` , can not login sucess,how can i solve this problem,looking forward to your answer .

**Comment by jfjallid** [comment]
Are you properly escaping the characters for your terminal?
Same problem if you don't specify your password as a cmdline argument?

Also, is your account a local account or a domain account?

**Comment by wqk151** [comment]
Thanks for your reply.

- I can't login properly even with the escape
- If don't specify a password, will be prompted to enter it, but it's also not work
- This is a domain account.

I use this demo also not work
```
    hostname := "127.0.0.1"
    options := smb.Options{
        Host:           hostname,
        Port:           445,
        Initiator:      &smb.NTLMInitiator{
            User:       "Administrator",
            Password:   "AdminPass123",
            Domain:     "",
        },
    }
    session, err := smb.NewConnection(options)
    if err != nil {
        fmt.Println(err)
        return
    }
    defer session.Close()
```

Also, if I use  `Hash`, how do I generate this hash, can you provide an example method?

**Comment by wqk151** [comment]
I tried this repository(`https://github.com/stacktitan/smb`) and can login successfully, the output is as follows
```
2024/04/10 13:47:10 [ DEBUG ]  Negotiating protocol
2024/04/10 13:47:10 [ DEBUG ]  Sending NegotiateProtocol request
2024/04/10 13:47:10 [ DEBUG ]  Unmarshalling NegotiateProtocol response
2024/04/10 13:47:10 [ DEBUG ]  Sending SessionSetup1 request
2024/04/10 13:47:10 [ DEBUG ]  Unmarshalling SessionSetup1 response
2024/04/10 13:47:10 [ DEBUG ]  Sending SessionSetup2 request
2024/04/10 13:47:10 [ DEBUG ]  Performing password-based authentication
2024/04/10 13:47:10 [ DEBUG ]  Unmarshalling SessionSetup2 response
2024/04/10 13:47:10 [ DEBUG ]  Completed NegotiateProtocol and SessionSetup
2024/04/10 13:47:10 [+] Signing is NOT required
2024/04/10 13:47:10 [+] Login successful
```

However, this repository is just a base and doesn't provide some practical methods, which are a bit difficult for me to implement

**Comment by jfjallid** [comment]
> Thanks for your reply.
> 
> - I can't login properly even with the escape
> - If don't specify a password, will be prompted to enter it, but it's also not work
> - This is a domain account.
> 
> I use this demo also not work
> ```
>     hostname := "127.0.0.1"
>     options := smb.Options{
>         Host:           hostname,
>         Port:           445,
>         Initiator:      &smb.NTLMInitiator{
>             User:       "Administrator",
>             Password:   "AdminPass123",
>             Domain:     "",
>         },
>     }
>     session, err := smb.NewConnection(options)
>     if err != nil {
>         fmt.Println(err)
>         return
>     }
>     defer session.Close()
> ```
> 
> Also, if I use  `Hash`, how do I generate this hash, can you provide an example method?

If you specify credentials from the cmdline, do you specify `--user model --domain example.com`?

If you use my example, domain should not be empty.

To convert a password to NT hash you can use a service such as https://md5decrypt.net/en/Ntlm/

**Comment by wqk151** [comment]
Thank you very much for your help, I found the cause of the problem, the username should be set to `model`, when I used python before, the username was set to `model@example.com`, and I can login normally, but go needs to be set to `model`, I don't know why, but now it works normally, thank you again for your help.

**Comment by jfjallid** [comment]
> Thank you very much for your help, I found the cause of the problem, the username should be set to `model`, when I used python before, the username was set to `model@example.com`, and I can login normally, but go needs to be set to `model`, I don't know why, but now it works normally, thank you again for your help.

No worries. By Python I assume you mean Impacket and if so they have a different way of parsing arguments than me. I've decided to split username and domain into two arguments.

**Comment by wqk151** [comment]
I'm using the python package is `pysmb`, demo like
```
from smb.SMBConnection import SMBConnection

server_ip = "192.168.1.10"            
username = "model@example.com" 
password = ""   
my_name = "" 
remote_name = "test"
conn = SMBConnection(username, password, my_name, remote_name, is_direct_tcp = True)   
assert conn.connect(server_ip, 445)
```

`my_name` can be empty, `remote_name` can be any string.

**Comment by jfjallid** [comment]
Okey, but regardless, each program has its own way of handling arguments. 

I'm glad that you identified the problem and that is works now. I will close this issue.
